MATCH (device:EdgeDevice {device_id: "h01"})
SET device.platform = "x86_64",
    device.smp_size = 2,
    device.smt_size = 6,
    device.release_date = "08/16/2017",
    device.bios_vendor = "Dell Inc.",
    device.bios_version = "2.5.5",
    device.gpu = false,
    device.humanized_ram_size = "62 GiB",
    device.ram_size = 65324808,
    device.device_type = "compute-broadwell",
    device.clock_speed = 1700000000,
    device.instruction_set = "x86-64",
    device.processor_model = "Intel Xeon",
    device.processor_description = "Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz",
    device.processor_vendor = "Intel",
    device.processor_version = "E5-2603 v4";

MATCH (device:EdgeDevice {device_id: "cicnano01"})
SET device.platform = "aarch64",
    device.smp_size = 1,
    device.smt_size = 4,
    device.gpu = true,
    device.gpu_count = 1,
    device.gpu_model = "Maxwell",
    device.gpu_vendor = "NVIDIA",
    device.humanized_ram_size = "3 GiB",
    device.ram_size = 4059016,
    device.device_type = "jetson-nano",
    device.clock_speed = 1479000000,
    device.instruction_set = "aarch64",
    device.processor_model = "Cortex-A57",
    device.processor_description = "ARM Cortex-A57",
    device.processor_vendor = "ARM";

MATCH (device:EdgeDevice {device_id: "cicnano02"})
SET device.platform = "aarch64",
    device.smp_size = 1,
    device.smt_size = 4,
    device.gpu = true,
    device.gpu_count = 1,
    device.gpu_model = "Maxwell",
    device.gpu_vendor = "NVIDIA",
    device.humanized_ram_size = "3 GiB",
    device.ram_size = 4059016,
    device.device_type = "jetson-nano",
    device.clock_speed = 1479000000,
    device.instruction_set = "aarch64",
    device.processor_model = "Cortex-A57",
    device.processor_description = "ARM Cortex-A57",
    device.processor_vendor = "ARM";

MATCH (device:EdgeDevice {device_id: "cicnano03"})
SET device.platform = "aarch64",
    device.smp_size = 1,
    device.smt_size = 4,
    device.gpu = true,
    device.gpu_count = 1,
    device.gpu_model = "Maxwell",
    device.gpu_vendor = "NVIDIA",
    device.humanized_ram_size = "3 GiB",
    device.ram_size = 4059016,
    device.device_type = "jetson-nano",
    device.clock_speed = 1479000000,
    device.instruction_set = "aarch64",
    device.processor_model = "Cortex-A57",
    device.processor_description = "ARM Cortex-A57",
    device.processor_vendor = "ARM";

MATCH (device:EdgeDevice {device_id: "cicnano04"})
SET device.platform = "aarch64",
    device.smp_size = 1,
    device.smt_size = 4,
    device.gpu = true,
    device.gpu_count = 1,
    device.gpu_model = "Maxwell",
    device.gpu_vendor = "NVIDIA",
    device.humanized_ram_size = "3 GiB",
    device.ram_size = 4059016,
    device.device_type = "jetson-nano",
    device.clock_speed = 1479000000,
    device.instruction_set = "aarch64",
    device.processor_model = "Cortex-A57",
    device.processor_description = "ARM Cortex-A57",
    device.processor_vendor = "ARM";
